### ISSUE TITLE
Arm designators: crashes after two pick-up attempts

### ISSUE THREAD

**Issue by svddries** [tue-robotics/robot_smach_states#21]
If the robot attempted two pick-ups, the arm designator does not return a value and an exception is thrown. Is this wanted behavior.

Right now, it is very hard to do more than two pick-ups using the GUI. We need a way to reset the arms, and reset the designators.

**Comment by LoyVanBeek** [comment]
Fixed in https://github.com/tue-robotics/robot_skills/commit/00dff3ff94369da5f0bd2ead85c65fec8e21da32. When the robot opens its hand, it drops everthing and thus the hand will be unoccupied. 
The designators for an arm will search for an unoccupied arm and this fixed makes arms unoccupied when it opens, not just when it places.
