### ISSUE TITLE
Navigate to symbolic 'near' is not working

### ISSUE THREAD

**Issue by reinzor** [tue-robotics/robot_smach_states#60]
Near area is calculated wrong, could also be a fault in ed_navigation but this has to be checked!

**Comment by LoyVanBeek** [comment]
In what way is it not working?

**Comment by reinzor** [comment]
Wrong area is calculated 

-Rein

**Comment by LoyVanBeek** [comment]
Which challenge, designator/entity, what area name?

**Comment by reinzor** [comment]
see r5cop challenge

-Rein

**Comment by LoyVanBeek** [comment]
Can also be tested with 
```bash
rosrun robot_smach_states simple_navigate.py amigo
```

If you change the object in https://github.com/tue-robotics/robot_smach_states/blob/master/examples/simple_navigate.py#L45 to 'plant' or 'trashbin' and 'near', the robot goes near them, so that works.
It also works when going 'near' the 'nightstand' or 'bar'.
It does not work for 'bookcase' or 'cabinet'. 

plant and trashbin are simple cylinders and the nightstand and the bar are boxes. 
bookcase and cabinet are compound shapes, so I think the convex hull of these may be incorrect.

**Comment by reinzor** [comment]
Nice!

-Rein
